# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6aea57afa667923b7262ea6ed76745d4333421d2b04b5c6ca679ae70d8bd586123a1647867f7d787194104eff98f5a1014d8fc70a01fcda756af090ed16516f

test:
  secret_key_base: e4b54c055cd0a47b7623f19f64aad97d23f352cad46b02430f0671c1b4d0112207a3239b57956aa9b98a86f05b467166e28b5ba929b2d0cb43ec27a2f9e2ed47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
